# Generated by Django 4.0.2 on 2022-02-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
    ]
