# Generated by Django 4.0.2 on 2022-02-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
